### ISSUE TITLE
System.IO.IOException: The network path was not found.

### ISSUE THREAD

**Issue by Acid-Crash** [ElPumpo/TinyNvidiaUpdateChecker#116]
Hi here recenly the app stopped working for me.
When applying debug parameter, I get the following error
I have GeForce GTX1060 6GB with v522.25

e:\Soft\TinyNvidiaUpdateChecker
λ TinyNvidiaUpdateChecker.v1.14.6.exe --debug
TinyNvidiaUpdateChecker v1.14.6

Arg: --debug

configFile: C:\Users\Acid_Crash\AppData\Local\Hawaii_Beach\TinyNvidiaUpdateChecker\app.config
CHECK_UPDATE: true
MINIMAL_INSTALL: true
DOWNLOAD_LOCATION: ru

Verifying internet connection . . . OK!

Verifying HAP MD5 hash . . . OK!
Generated hash: F9-72-91-2B-04-C7-FD-13-B7-55-D9-57-B3-66-EB-3F
Known hash:     F9-72-91-2B-04-C7-FD-13-B7-55-D9-57-B3-66-EB-3F

winVer: 10
osID:   57
verOrg: 10.0.19045.0

langID:   17
cultName: uk-UA

Searching for Updates . . . OK!
offlineVer: 1.14.6
onlineVer:  1.14.6

Retrieving GPU information . . . ERROR!
System.IO.IOException: The network path was not found.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding)
   at HtmlAgilityPack.HtmlDocument.DetectEncoding(String path)
   at HtmlAgilityPack.HtmlDocument.DetectEncodingAndLoad(String path, Boolean detectEncoding)
   at HtmlAgilityPack.HtmlWeb.Load(Uri uri, String method)
   at HtmlAgilityPack.HtmlWeb.Load(String url)
   at TinyNvidiaUpdateChecker.MainConsole.GpuInfo()
gpuURL: https://www.nvidia.com/Download/processDriver.aspx?psid=98&pfid=756&osid=57&lid=17&dtcid=1&ctk=0
downloadURL:
pdfURL:
releaseDate: 01.01.0001
downloadFileSize:  0 MB (0,00 bytes)
OfflineGPUVersion: 522.25
OnlineGPUVersion:  000.00
Your current GPU driver is newer than remote!
Your GPU drivers are up-to-date!

Press any key to exit...

**Comment by Acid-Crash** [comment]
Tried to delete temporary files and tried to pick EN locale.
The issue is still here


e:\Soft\TinyNvidiaUpdateChecker
λ TinyNvidiaUpdateChecker.v1.14.6.exe --debug
TinyNvidiaUpdateChecker v1.14.6

Arg: --debug

configFile: C:\Users\Acid_Crash\AppData\Local\Hawaii_Beach\TinyNvidiaUpdateChecker\app.config
Generating configuration file, this only happens once.

CHECK_UPDATE: true
MINIMAL_INSTALL: false
DOWNLOAD_LOCATION: us

Verifying internet connection . . . OK!

Verifying HAP MD5 hash . . . OK!
Generated hash: F9-72-91-2B-04-C7-FD-13-B7-55-D9-57-B3-66-EB-3F
Known hash:     F9-72-91-2B-04-C7-FD-13-B7-55-D9-57-B3-66-EB-3F

winVer: 10
osID:   57
verOrg: 10.0.19045.0

langID:   17
cultName: uk-UA

Searching for Updates . . . OK!
offlineVer: 1.14.6
onlineVer:  1.14.6

Retrieving GPU information . . . ERROR!
System.IO.IOException: The network path was not found.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding)
   at HtmlAgilityPack.HtmlDocument.DetectEncoding(String path)
   at HtmlAgilityPack.HtmlDocument.DetectEncodingAndLoad(String path, Boolean detectEncoding)
   at HtmlAgilityPack.HtmlWeb.Load(Uri uri, String method)
   at HtmlAgilityPack.HtmlWeb.Load(String url)
   at TinyNvidiaUpdateChecker.MainConsole.GpuInfo()
gpuURL: https://www.nvidia.com/Download/processDriver.aspx?psid=98&pfid=756&osid=57&lid=17&dtcid=1&ctk=0
downloadURL:
pdfURL:
releaseDate: 01.01.0001
downloadFileSize:  0 MB (0,00 bytes)
OfflineGPUVersion: 522.25
OnlineGPUVersion:  000.00
Your current GPU driver is newer than remote!
Your GPU drivers are up-to-date!

Press any key to exit...

**Comment by ElPumpo** [comment]
So yea, NVIDIA changed their website code. This is a problem in itself that we don't use the public API to get driver info.. I wont be able to fix this until next week

**Comment by ElPumpo** [comment]
Fixed in new version!

**Comment by Acid-Crash** [comment]
Confirming, the update seems to be fixed the issue
