### ISSUE TITLE
Windows Chassis Type 1 (Others) wrongly identify as desktop but is notebook

### ISSUE THREAD

**Issue by awsms** [ElPumpo/TinyNvidiaUpdateChecker#134]
```
TinyNvidiaUpdateChecker v1.15.2

Verifying internet connection . . . OK!

Retrieving GPU information . . . ERROR!
GPU metadata for your card does not exist! Please file an issue on GitHub and include the following information:

gpuName:    GeForce RTX 3060 Laptop GPU
isNotebook: False

Press any key to exit...
```
note: i'm using it in a GPU passthroughed VM (VFIO)

**Comment by awsms** [comment]
error I had on v1.14.6

```Verifying internet connection . . . OK!

Verifying HAP MD5 hash . . . OK!

Retrieving GPU information . . . ERROR!
System.UriFormatException: Invalid URI: The format of the URI could not be determined.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at HtmlAgilityPack.HtmlWeb.Load(String url)
   at TinyNvidiaUpdateChecker.MainConsole.GpuInfo()
Your current GPU driver is newer than remote!
Your GPU drivers are up-to-date!

Press any key to exit...
```

**Comment by ElPumpo** [comment]
Yea forget that old version lol it wont ever work.

Are you on a notebook? Because `isNotebook` is reported as `false`.Open powershell and enter the following

` Get-WmiObject -class win32_systemenclosure | select  Caption,chassisTypes`

Please show a screenshot of the responce. I probably don't have your chassis type in my code.

**Comment by ElPumpo** [comment]
@awsms you still there?

**Comment by ElPumpo** [comment]
Closing because of inactivity

**Comment by awsms** [comment]
Hey, sorry I haven't used my Windows partition for months now.


> Yea forget that old version lol it wont ever work.
> 
> Are you on a notebook? Because `isNotebook` is reported as `false`.Open powershell and enter the following
> 
> ` Get-WmiObject -class win32_systemenclosure | select Caption,chassisTypes`
> 
> Please show a screenshot of the responce. I probably don't have your chassis type in my code.

output of the command is
```
Caption          chassisTypes
-------          ------------
System Enclosure {1}
```

I'm on a laptop (Lenovo Legion 5), and running win10 in a virtual machine with the NVIDIA GPU passthroughed into it.

**Comment by ElPumpo** [comment]
Is this still an issue?

**Comment by awsms** [comment]
> @awsms hi is this still an issue?

Indeed, I did finally use the nvidia-display-driver package from chocolatey since I couldn't get TNUC to work in my VM.
Is the output of ` Get-WmiObject -class win32_systemenclosure | select Caption,chassisTypes` abnormal in the previous comment?

**Comment by ElPumpo** [comment]
Okay your chassis type is 1 which is defined as "Others".

TNUC does not currently classify type 1 as notebook. I will fix this in the coming release.

So it searches for a desktop driver for a notebook GPU.

**Comment by ElPumpo** [comment]
Okay I will fix this but is there no way for VFIO to change the chassis type reported to Windows?

It is risky because 1 is identified as "Others". It might have little to do with notebook / desktop GPU but I can't be sure... Ideally this entire chassis type should not be used...

**Comment by ElPumpo** [comment]
Adressed in v1.17.0
