### ISSUE TITLE
Different PNP Device ID length causing ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by GalaxyBound** [ElPumpo/TinyNvidiaUpdateChecker#217]
The new 1.18.0 version throws an exception on launch. It appears to be referencing a path not available on my system (C:\Users\Samuel\Documents\GitHub\). Here is the log:

```
TinyNvidiaUpdateChecker v1.18.0

Verifying internet connection . . . OK!

Searching for Updates . . . OK!

Retrieving GPU information . . . Unhandled exception. System.ArgumentOutOfRangeException: Index and length must refer to a location within the string. (Parameter 'length')
   at System.String.ThrowSubstringArgumentOutOfRange(Int32 startIndex, Int32 length)
   at TinyNvidiaUpdateChecker.MainConsole.GetDriverMetadata() in C:\Users\Samuel\Documents\GitHub\TinyNvidiaUpdateChecker\TinyNvidiaUpdateChecker\MainConsole.cs:line 491
   at TinyNvidiaUpdateChecker.MainConsole.Main(String[] args) in C:\Users\Samuel\Documents\GitHub\TinyNvidiaUpdateChecker\TinyNvidiaUpdateChecker\MainConsole.cs:line 151
```

My system has a discrete Nvidia GPU and integrated graphics. Version 1.17.1 still works fine.

**Comment by ElPumpo** [comment]
Hi Galaxy and thanks for your report. Will investigate

**Comment by ElPumpo** [comment]
Okay that's fixed now, my fault. I'm fixing another bug too and then we have a new release.
