### ISSUE TITLE
Self-update fails when running from shell in a different directory

### ISSUE THREAD

**Issue by Antelope13** [ElPumpo/TinyNvidiaUpdateChecker#224]
TinyNvidiaUpdateChecker is installed in a folder on my PATH. When running from shell, I encounter the following error:

```
PS C:\Users\example> TinyNvidiaUpdateChecker
TinyNvidiaUpdateChecker v1.18.2

Verifying internet connection . . . OK!

Searching for Update . . . OK!
There is a update available for TinyNvidiaUpdateChecker!
Update failed

Unhandled exception. System.IO.FileNotFoundException: Could not find file 'C:\Users\example\TinyNvidiaUpdateChecker.exe.old'.
File name: 'C:\Users\example\TinyNvidiaUpdateChecker.exe.old'
   at System.IO.File.Move(String sourceFileName, String destFileName, Boolean overwrite)
   at TinyNvidiaUpdateChecker.Handlers.UpdateHandler.UpdateNow(String[] args) in C:\Users\Samuel\Documents\GitHub\TinyNvidiaUpdateChecker\TinyNvidiaUpdateChecker\Handlers\UpdateHandler.cs:line 103
   at TinyNvidiaUpdateChecker.Handlers.UpdateHandler.SearchForUpdate(String[] args) in C:\Users\Samuel\Documents\GitHub\TinyNvidiaUpdateChecker\TinyNvidiaUpdateChecker\Handlers\UpdateHandler.cs:line 42
   at TinyNvidiaUpdateChecker.MainConsole.Main(String[] args) in C:\Users\Samuel\Documents\GitHub\TinyNvidiaUpdateChecker\TinyNvidiaUpdateChecker\MainConsole.cs:line 151
```

It also fails with the same error when using the full path:
`D:\bin\TinyNvidiaUpdateChecker\TinyNvidiaUpdateChecker.exe`

Running from its directory fixes the problem:

```
PS C:\Users\example> cd C:\bin\tnuc
PS C:\bin\tnuc> TinyNvidiaUpdateChecker
TinyNvidiaUpdateChecker v1.18.2

Verifying internet connection . . . OK!

Searching for Update . . . OK!
There is a update available for TinyNvidiaUpdateChecker!

Downloading update . . . OK!
Validating checksum . . . OK!

Relaunching now!
```

**Comment by ElPumpo** [comment]
Hi Ante. Thanks for the bug report. I will fix that
