### ISSUE TITLE
Error: unknown option "optemp"

### ISSUE THREAD

**Issue by PulsarFTW** [ElPumpo/TinyNvidiaUpdateChecker#239]
Fantastic software, having a small issue recently and not sure if it's something I can fix myself.

Version: 1.19.1
Windows Version: 23H2 (22631.4317)
Dotnet Runtime: 8.0.10

When running the software it finds an update and I press to install, as it gets to the extracting stage I get the error 
`Error: unknown option "optemp"`  

```
TinyNvidiaUpdateChecker v1.19.1

Arg: --debug

configFile: C:\Users\USER\AppData\Local\Hawaii_Beach\TinyNvidiaUpdateChecker\app.config
CHECK_UPDATE: true
MINIMAL_INSTALL: true
DOWNLOAD_LOCATION: uk
DRIVER_TYPE: grd

Verifying internet connection . . . OK!

Searching for Update . . . OK!
offlineVer: 1.19.1
onlineVer:  1.19.1

Retrieving GPU information . . . OK!
gpuId:       933
osId:        135
isDchDriver: True
downloadURL: https://uk.download.nvidia.com/Windows/566.14/566.14-desktop-win10-win11-64bit-international-dch-whql.exe
pdfURL:      https://us.download.nvidia.com/Windows/566.14/566.14-win11-win10-release-notes.pdf
releaseDate: 12/11/2024
downloadFileSize:  689 MiB
OfflineGPUVersion: 566.03
OnlineGPUVersion:  566.14
There is a new GPU driver available to download!

Extracting drivers
```
after pressing ok on the error popup error it continues and I get the following errors:
```
Extracting drivers . . . Unhandled exception. System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\USER\AppData\Local\Temp\566.14\temp'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserDirectories(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.Directory.GetDirectories(String path, String searchPattern, EnumerationOptions enumerationOptions)
   at TinyNvidiaUpdateChecker.Handlers.ComponentHandler.ParseComponentData(String driverRootPath) in C:\Users\Samuel\Documents\GitHub\TinyNvidiaUpdateChecker\TinyNvidiaUpdateChecker\Handlers\ComponentHandler.cs:line 14
   at TinyNvidiaUpdateChecker.MainConsole.MakeInstaller(Boolean silent, String savePath, String fileName) in C:\Users\Samuel\Documents\GitHub\TinyNvidiaUpdateChecker\TinyNvidiaUpdateChecker\MainConsole.cs:line 965
   at TinyNvidiaUpdateChecker.MainConsole.DownloadDriverQuiet(Boolean minimized, String downloadURL) in C:\Users\Samuel\Documents\GitHub\TinyNvidiaUpdateChecker\TinyNvidiaUpdateChecker\MainConsole.cs:line 815
   at TinyNvidiaUpdateChecker.MainConsole.DownloadDriver(String downloadURL) in C:\Users\Samuel\Documents\GitHub\TinyNvidiaUpdateChecker\TinyNvidiaUpdateChecker\MainConsole.cs:line 760
   at TinyNvidiaUpdateChecker.MainConsole.Main(String[] args) in C:\Users\Samuel\Documents\GitHub\TinyNvidiaUpdateChecker\TinyNvidiaUpdateChecker\MainConsole.cs:line 267
```

Any help or suggestions would be greatly appreciated - thanks again for the software, it's been working well since I installed 4+ months ago until the last few weeks.

**Comment by PulsarFTW** [comment]
I realise what the issue is so I apologise for the bug report. I'm leaving this comment here in the (unlikely) event that someone has the same issue.

I was troubleshooting another problem a few weeks ago and installed an old version of winrar for testing. 
This version of winrar was not compatible with the commands - probably because it was 6+ years old. Uninstalling the old winrar defaulted TinyNvidiaUpdateChecker back to 7zip and it works perfectly now.
