### ISSUE TITLE
Remote name could not be resolved

### ISSUE THREAD

**Issue by kaizengamer** [ElPumpo/TinyNvidiaUpdateChecker#92]
Retrieving GPU information . . . ERROR!
System.Net.WebException: The remote name could not be resolved: 'us.down.download.nvidia.com'
   at System.Net.HttpWebRequest.GetResponse()
   at TinyNvidiaUpdateChecker.MainConsole.GpuInfo()
Your current GPU driver is newer than remote!
Your GPU drivers are up-to-date!

Job done! Press any key to exit.

**Comment by kaizengamer** [comment]
This was the result of making the work-around fix before issue 86 was resolved.  Fixed by deleting C:\Users\scott\AppData\Local\Hawaii_Beach\TinyNvidiaUpdateChecker\app.config and re-running program.
