### ISSUE TITLE
Should download HAP next to the binary instead of current working directory

### ISSUE THREAD

**Issue by alyti** [ElPumpo/TinyNvidiaUpdateChecker#94]
If used via scoop (#58) the binary crashes unless run from CWD (afterwards it's fine though):

```
PS C:\Users\USERNAME\scoop\apps\tinynvidiaupdatechecker\current> ls

    Directory: C:\Users\USERNAME\scoop\apps\tinynvidiaupdatechecker\current

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---           5/11/2021  1:28 PM         165376 HtmlAgilityPack.dll
-a---           5/11/2021  1:28 PM             60 install.json
-a---           5/11/2021  1:24 PM            821 manifest.json
-a---           5/11/2021  1:28 PM         168448 TinyNvidiaUpdateChecker.exe

PS C:\Users\USERNAME\scoop\apps\tinynvidiaupdatechecker\current> rm .\HtmlAgilityPack.dll
PS C:\Users\USERNAME\scoop\apps\tinynvidiaupdatechecker\current> cd ..
PS C:\Users\USERNAME\scoop\apps\tinynvidiaupdatechecker> ls

    Directory: C:\Users\USERNAME\scoop\apps\tinynvidiaupdatechecker

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----           5/12/2021  6:29 PM                1.14.2
l-r--           5/11/2021  1:28 PM                current -> C:\Users\USERNAME\scoop\apps\tinynvidiaupdatechecker\1.14.2

PS C:\Users\USERNAME\scoop\apps\tinynvidiaupdatechecker> tinynvidiaupdatechecker.exe
TinyNvidiaUpdateChecker v1.14.2

Copyright (C) 2016-2020 Hawaii_Beach
This program comes with ABSOLUTELY NO WARRANTY
This is free software, and you are welcome to redistribute it
under certain conditions. Licensed under GPLv3.

Verifying internet connection . . . OK!

Attempting to download HtmlAgilityPack.dll . . . OK!


Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'HtmlAgilityPack, Version=1.11.23.0, Culture=neutral, PublicKeyToken=bd319b19eaf3b43a' or one of its dependencies. The system cannot find the file specified.
   at TinyNvidiaUpdateChecker.MainConsole.SearchForUpdates()
   at TinyNvidiaUpdateChecker.MainConsole.Main(String[] args)
PS C:\Users\USERNAME\scoop\apps\tinynvidiaupdatechecker>
```

**Comment by ElPumpo** [comment]
Yes that's very wrong, needs a fix

**Comment by ElPumpo** [comment]
Sorry for the very long delay on the issue, not been active at all. Fixed now at least. Thanks for reporting issues
